# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: "3.4"

services:
  authservice:
    image: authservice
    build:
      context: .
      dockerfile: Backend/Microservices/auth-service/Dockerfile
    ports:
      - 5280:5280

  userservice:
    image: userservice
    build:
      context: .
      dockerfile: Backend/Microservices/user-service/Dockerfile
    ports:
      - 5081:5081

  apigateway:
    image: apigateway
    build:
      context: .
      dockerfile: Backend/ApiGateway/Dockerfile
    ports:
      - 5078:5078

  usersdb:
    image: postgres:latest
    container_name: usersdb
    environment:
      - POSTGRES_DB=User
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/usersdb:/var/lib/postgresql/data
    ports:
      - 5432:5432
